### ISSUE TITLE
Locator

### ISSUE THREAD

**Issue by Dyronix** [SamuelAsherRivello/rmc-mini-mvcs#1]
Adding multiple models to the locator is not feasible within the current framework. This limitation arises from the fact that the function evaluates the base type rather than the runtime type of the object. To address this issue, I have implemented a resolution in my forked repository of the project: https://github.com/Dyronix/rmc-mini-mvcs

**Comment by SamuelAsherRivello** [comment]
Great feedback. I have since updated the Locator and will look at it soon with your feedback. Thanks.

**Comment by SamuelAsherRivello** [comment]
@Dyronix I've completed a newer, bigger refactor. I have an issue before it deploys to NPM. It'll be v2.0.0 or newer.

**Comment by SamuelAsherRivello** [comment]
@Dyronix Does your issue exist in the latest release?

**Comment by SamuelAsherRivello** [comment]
@Dyronix This limitation no longer exists. There are now included 'Advanced' samples you can checkout that use a new structure to allow for multiple "concerns" of each type; models, views, controllers, services. It also has a new feature called 'Feature' that allows you to add and remove groups of concerns
