### ISSUE TITLE
Auto-loading of the input system behaved falsely, due to a stuck EditorPrefs variable

### ISSUE THREAD

**Issue by KReguieg** [SamuelAsherRivello/rmc-mini-mvcs#6]
As described by  @SamuelAsherRivello here: https://github.com/SamuelAsherRivello/rmc-mini-mvcs/pull/5#issuecomment-1878000588 the auto-loading of the input system behaved falsely due to a stuck _EditorPrefs_ variable.

I used a Editor feature that behaves like PlayerPrefs. It is called EditorPrefs and creates data point in the _Registry_ of the users PC.

```cs
EditorPrefs.SetBool("PackageInstalled", false);
EditorPrefs.SetBool("PackageInstalled", true);
```

So if you ever installed it and didn't click the _'Reset PackageInstalled Switch'_ the _PackageInstalled_ variable in the registry stays _true_. I think I might be able to provide a fix. By resetting the _PackageInstalled Variable if it exists to _false_ everytime it checks and only set it to _true_ if it is present already.

```cs
if (EditorPrefs.HasKey("PackageInstalled"))
    EditorPrefs.SetBool("PackageInstalled", false);
```

Then we can also get rid of the button. (Where I also made a variable name copy paste mistake. 😅)

_Originally posted by @KReguieg in https://github.com/SamuelAsherRivello/rmc-mini-mvcs/issues/5#issuecomment-1879834581_

**Comment by SamuelAsherRivello** [comment]
Thanks! I'll check it soon

**Comment by KReguieg** [comment]
Tested with:

New project, no registry key available and it works. ✅
Existing project, registry key available and both values and it works as well. ✅

Will create a new PR from a fix branch. 🍻

**Comment by KReguieg** [comment]
Corresponding PR: #7
